### ISSUE TITLE
mailto created in step 6a

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/bluexp-cloud-volumes-service-gcp#14]
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-service-gcp/task-set-up-google-cloud.html

### Page title

Set up Google Cloud

### Summary

The sample in step 6a is converted to a mailto link. It should be escaped or formatted to prevent link creation.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Thank you for catching this. It's been fixed.
